In [2]:
import openai

openai.api_key = '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' # for my personal account

In [3]:
import pandas as pd
import os

directory_path = '../data/transcripts_from_whisper/'

transcripts_df = pd.DataFrame(columns=["id", "text"])

# extract ids from filenames and text from files
for filename in os.listdir(directory_path):
    if filename.endswith(".txt"):
        file_id = filename[:3]
        with open(os.path.join(directory_path, filename), "r") as file:
            file_contents = file.read()
        transcripts_df = transcripts_df.append({"id": file_id, "text": file_contents}, ignore_index=True)

transcripts_df["id"] = transcripts_df["id"].astype("int64")

labels_dev_df = pd.read_csv('../data/labels/dev_split.csv')
labels_dev_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

labels_train_df = pd.read_csv('../data/labels/train_split.csv')
labels_train_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

labels_test_df = pd.read_csv('../data/labels/test_split.csv')
labels_test_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

# merge dataframes on id
df_dev = pd.merge(labels_dev_df, transcripts_df, on='id')
df_train = pd.merge(labels_train_df, transcripts_df, on='id')
df_test = pd.merge(labels_test_df, transcripts_df, on='id')

df_dev = df_dev.sort_values(by="id")
df_train = df_train.sort_values(by="id")
df_test = df_test.sort_values(by="id")

df_dev.head()

/var/folders/p4/x9h3xj457tb303r8d777sm7r0000gn/T/ipykernel_13824/119909400.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transcripts_df = transcripts_df.append({"id": file_id, "text": file_contents}, ignore_index=True)
/var/folders/p4/x9h3xj457tb303r8d777sm7r0000gn/T/ipykernel_13824/119909400.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transcripts_df = transcripts_df.append({"id": file_id, "text": file_contents}, ignore_index=True)
/var/folders/p4/x9h3xj457tb303r8d777sm7r0000gn/T/ipykernel_13824/119909400.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  transcripts_df = transcripts_df.append({"id": file_id, "text": file_contents}, ignore_index=True)
/var/folders/p4/x9h3xj457tb303r8d777sm7r0000gn/T/ipyker

id  Gender  PHQ_Binary  PHQ_Score  PCL-C (PTSD)  PTSD Severity  \
0  300    male           0          2             0             25   
1  301    male           0          3             0             17   
2  306  female           0          0             0             21   
3  317    male           0          8             1             51   
4  320  female           0         11             1             64   

                                                text  
0   which will record your body. So I'll show you...  
1   Yeah, there's all sorts of different studies ...  
2   Okay, looks like we're good. But let's move a...  
3   Okay. How long is this? This is probably goin...  
4   Okay, everything looks good. Okay. Perfect. O...

In [4]:
max(df_train['PHQ_Score'])

23

In [105]:
# import pandas as pd

# transcripts_df = pd.read_csv('../data/transcripts.csv')
# # remove first column
# transcripts_df = transcripts_df.iloc[:,1:]
# transcripts_df.columns = ['id', 'text']

# labels_dev_df = pd.read_csv('../data/labels/dev_split.csv')
# labels_dev_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

# labels_train_df = pd.read_csv('../data/labels/train_split.csv')
# labels_train_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

# labels_test_df = pd.read_csv('../data/labels/test_split.csv')
# labels_test_df.columns = ['id', 'Gender', 'PHQ_Binary', 'PHQ_Score', 'PCL-C (PTSD)', 'PTSD Severity']

# # merge dataframes on id
# df_dev = pd.merge(labels_dev_df, transcripts_df, on='id')
# df_train = pd.merge(labels_train_df, transcripts_df, on='id')
# df_test = pd.merge(labels_test_df, transcripts_df, on='id')

# df_dev.head()

In [106]:
# import re
# import nltk
# from nltk.corpus import stopwords
# from nltk.stem import PorterStemmer
# nltk.download('stopwords')

# def clean_text(text):
#     # remove punctuation and special characters
#     text = re.sub(r'[^\w\s]', '', text)

#     # lowercase all words
#     text = text.lower()

#     # remove stop words
#     stop_words = set(stopwords.words('english'))
#     text = [word for word in text.split() if word not in stop_words]

#     # stem/lemmatize words
#     # stemmer = PorterStemmer()
#     # text = [stemmer.stem(word) for word in text]

#     # remove numbers
#     # text = [word for word in text if not word.isdigit()]

#     return " ".join(text)

# # clean all transcripts
# df_dev['text'] = df_dev['text'].apply(clean_text)
# df_train['text'] = df_train['text'].apply(clean_text)
# df_test['text'] = df_test['text'].apply(clean_text)

# df_dev.head()

In [5]:
# !!!!! this is the prompt that we will use for Chat-GPT API !!!!!
# prompt = """ Here is an interview with a person who might have depression. Determine if the text might be relevant to depression. Explain your answer in a verbose manner.  """
# prompt = """  I am sending a text from an interview with a person. Can you tell me  features that can be clues for depression in the text? Additionally, mention the positive aspects in the person's interview if there is any. Please don't present features in a numbered list and explain your answer in a verbose and detail manner. Here is the text: """
# prompt = """  I am sending a text from an interview with a person. Can you tell me features that are clues for depression detection in the text? Here is the text: """
# prompt = """ I am sending a transcript of an interview with a person. What are the key linguistic features that are indicative of depression in written text? Avoid being overly pessimistic and solely focusing on negative features. Be sure to include positive attributes and responses of the person as well. Be concise and to the point. Here is the text: """
prompt1 = """ Your task is to read the following text which is an interview with a person and to summarize the key points that might be related to the depression of the person. Please be concise and to the point."""
# prompt 1 results:
# rmse for train:  5.639914434096471
# mae for train:  4.253329681080664
# rmse for dev:  5.315697780631046
# mae for dev:  3.9190065015199598
# rmse for test:  5.872976836334969
# mae for test:  4.730438183491851
prompt2 = """ Your task is to read the following text which is an interview with a person and to give a number from 0 to 100 that how likely is that this person has depression. 
Only give a number and do not explain your answer. """

In [8]:
# GPT-3 cost estimator for all completions
from transformers import GPT2TokenizerFast

tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")

token_counts = []
# for all tokens in all transcripts in dev, train, and test sets
for text in df_dev['text'].tolist() + df_train['text'].tolist() + df_test['text'].tolist():
    # tokenize text
    tokens = tokenizer.encode(text)
    # tokenize prompt
    prompt_tokens = tokenizer.encode(prompt1)

    # append token count to list
    token_counts.append(len(tokens) + len(prompt_tokens) + 512)

# Final cost estimataion
print(f'Estimated cost: ${(sum(token_counts) / 1000 * 0.002)}')

Token indices sequence length is longer than the specified maximum sequence length for this model (1142 > 1024). Running this sequence through the model will result in indexing errors


Estimated cost: $1.3496780000000002


In [6]:
import requests

def make_prompt(prompt, text):
    return """{}\nHere is the interview between triple backticks:\n```{}```""".format(prompt, text)

# extract ChatGPT completions for each transcript
def get_completions(prompt, text):
    prompt = make_prompt(prompt, text)
    # send request to API
    response = requests.post(
        "http://localhost:4100/parallel-requests",
        json={"prompts": prompt}
    )
    # get response
    response = response.json()
    return response["response"]

def get_completions_batch(prompt, texts):
    prompts = [make_prompt(prompt, text) for text in texts]
    prompts = "---".join(prompts)

    # send request to API
    response = requests.post(
        "http://localhost:4100/parallel-requests",
        json={"prompts": prompts}
    )

    # get response
    response = response.json()
    return response["response"]
    

In [ ]:
# Explore the result
# get completion for the first transcript in the dev set
id = 633
# find dv_dev row with id
row = df_train[df_train['id'] == id]
# get the value of the text column
text = row['text'].values[0]
print('This is the text:')
print(make_prompt(prompt1, text))
print('------------------------------------')
print('This is the completion:')
completions = get_completions(prompt1, text)
print(completions)

In [ ]:
# Now we're sure that the prompt and completion are working as expected
# Let's extract completions for all transcripts in the train, dev, and test sets
# we will do this in batches of 10 to prevent API rate limits

# get complettions in parallel in batches of 10
# df_dev['completions'] = ''
# for i in range(0, len(df_dev), 10):
#     print(f'Getting completions for dev transcripts {i} to {i+10}...')
#     # create a new column for completions
#     completions = get_completions_batch(prompt, df_dev['text'][i:i+10])
#     # convert list of completions to dataframe
#     df_completions = pd.DataFrame(completions, columns=['completions'])
#     # add completions to df_dev
#     df_dev['completions'][i:i+10] = df_completions['completions']

# df_train['completions'] = ''
# for i in range(0, len(df_train), 10):
#     print(f'Getting completions for train transcripts {i} to {i+10}...')
#     # create a new column for completions
#     completions = get_completions_batch(prompt1, df_train['text'][i:i+10])
#     # convert list of completions to dataframe
#     df_completions = pd.DataFrame(completions, columns=['completions'])
#     # add completions to df_dev
#     df_train['completions'][i:i+10] = df_completions['completions']


# df_test['completions'] = ''
# for i in range(0, len(df_test), 10):
#     print(f'Getting completions for test transcripts {i} to {i+10}...')
#     # create a new column for completions
#     completions = get_completions_batch(prompt, df_test['text'][i:i+10])
#     # convert list of completions to dataframe
#     df_completions = pd.DataFrame(completions, columns=['completions'])
#     # add completions to df_dev
#     df_test['completions'][i:i+10] = df_completions['completions']

In [ ]:
# df_train.to_csv('df_train_prompt_1.csv', index=False)
# df_dev.to_csv('df_dev_prompt_1.csv', index=False)
# df_test.to_csv('df_test_prompt_1.csv', index=False)

In [7]:
df_train = pd.read_csv('df_train_prompt_3_firstperson.csv')
df_dev = pd.read_csv('df_dev_prompt_3_firstperson.csv')
df_test = pd.read_csv('df_test_prompt_3_firstperson.csv')
df_test.head()

id  Gender  PHQ_Binary  PHQ_Score  PCL-C (PTSD)  PTSD Severity  \
0  600  female           0          5             0           23.0   
1  602  female           1         13             1           67.0   
2  604    male           1         12             0           30.0   
3  605    male           0          2             0           23.0   
4  606  female           0          5             0           46.0   

                                                text  \
0   Alright, there you are. Perfect. So you're go...   
1   This is super neat. I like this. Me either at...   
2   So if you could just say 1, 2, 3, 4, 5. 1, 2,...   
3   I'm going to bring up our virtual human for a...   
4   Okay, I just got it. I just got it new. So, o...   

                                         completions  
0  I was diagnosed with depression in 2002 after ...  
1  I have been diagnosed with PTSD almost two yea...  
2  I have not been diagnosed with depression, but...  
3  I was interviewed by a virtual human where I r...  
4  The interviewee seems to have a negative attit...

In [8]:
df_train['completions'] = df_train['completions'].astype('string')
df_dev['completions'] = df_dev['completions'].astype('string')
df_test['completions'] = df_test['completions'].astype('string')

In [9]:
print(df_test.loc[df_test['completions'].str.len() == 0])

Empty DataFrame
Columns: [id, Gender, PHQ_Binary, PHQ_Score, PCL-C (PTSD), PTSD Severity, text, completions]
Index: []


In [10]:
df_dev.head()

id  Gender  PHQ_Binary  PHQ_Score  PCL-C (PTSD)  PTSD Severity  \
0  300    male           0          2             0             25   
1  301    male           0          3             0             17   
2  306  female           0          0             0             21   
3  317    male           0          8             1             51   
4  320  female           0         11             1             64   

                                                text  \
0   which will record your body. So I'll show you...   
1   Yeah, there's all sorts of different studies ...   
2   Okay, looks like we're good. But let's move a...   
3   Okay. How long is this? This is probably goin...   
4   Okay, everything looks good. Okay. Perfect. O...   

                                         completions  
0  I have not found any key points related to dep...  
1  I work as an administrative assistant through ...  
2  I had an interview with a computer program des...  
3  I moved from New York to start over, and it wa...  
4  I was interviewed by a virtual human who asked...

In [ ]:
# # print df_train that completions is empty
# # df_train[df_train['completions'] == '']

# # for rows with empty completions
# for i in range(0, len(df_train)):
#     if df_train['completions'][i] == '':
#         print(i)
#         print(df_train['id'][i])
#         # # find file that starts with id
#         file_path = '../data/transcripts_from_whisper/' + str(df_train['id'][i]) + '_whisper.txt'
#         # open file
#         with open(file_path, 'r') as file:
#             # read file
#             text = file.read()
#             print(text)
#             df_train['text'][i] = text

In [ ]:
# non_nan_df_train = df_train.dropna()
# non_nan_df_dev = df_dev.dropna()
# non_nan_df_test = df_test.dropna()

# non_nan_df_train = non_nan_df_train.reset_index(drop=True)
# non_nan_df_dev = non_nan_df_dev.reset_index(drop=True)
# non_nan_df_test = non_nan_df_test.reset_index(drop=True)

In [50]:
# Print layer names
model = AutoModelForSequenceClassification.from_pretrained("rafalposwiata/deproberta-large-depression", output_hidden_states=True)
for name, param in model.named_parameters():
    print(name)

roberta.embeddings.word_embeddings.weight
roberta.embeddings.position_embeddings.weight
roberta.embeddings.token_type_embeddings.weight
roberta.embeddings.LayerNorm.weight
roberta.embeddings.LayerNorm.bias
roberta.encoder.layer.0.attention.self.query.weight
roberta.encoder.layer.0.attention.self.query.bias
roberta.encoder.layer.0.attention.self.key.weight
roberta.encoder.layer.0.attention.self.key.bias
roberta.encoder.layer.0.attention.self.value.weight
roberta.encoder.layer.0.attention.self.value.bias
roberta.encoder.layer.0.attention.output.dense.weight
roberta.encoder.layer.0.attention.output.dense.bias
roberta.encoder.layer.0.attention.output.LayerNorm.weight
roberta.encoder.layer.0.attention.output.LayerNorm.bias
roberta.encoder.layer.0.intermediate.dense.weight
roberta.encoder.layer.0.intermediate.dense.bias
roberta.encoder.layer.0.output.dense.weight
roberta.encoder.layer.0.output.dense.bias
roberta.encoder.layer.0.output.LayerNorm.weight
roberta.encoder.layer.0.output.LayerNorm

In [57]:
# extract deproberta features from column df['text']
from sentence_transformers import SentenceTransformer
import numpy as np
import torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("rafalposwiata/deproberta-large-depression")
model = AutoModelForSequenceClassification.from_pretrained("rafalposwiata/deproberta-large-depression", output_hidden_states=True)

# model = SentenceTransformer('all-mpnet-base-v2')

# # first convert NaNs to empty strings
# df_train['completions'] = df_train['completions'].fillna('')
# df_dev['completions'] = df_dev['completions'].fillna('')
# df_test['completions'] = df_test['completions'].fillna('')

X_train = df_train['completions']
X_dev = df_dev['completions']
X_test = df_test['completions']

print(len(X_train))
print(len(X_dev))
print(len(X_test))

y_train = np.array(df_train['PHQ_Score'])
y_dev = np.array(df_dev['PHQ_Score'])
y_test = np.array(df_test['PHQ_Score'])

# extract features from train data
X_train_features = []
for i in range(len(X_train)):
    # print('i train: ', i)
    input_ids = torch.tensor(tokenizer.encode(X_train[i], add_special_tokens=True)).unsqueeze(0)  # Batch size 1
    outputs = model(input_ids)
    
    # get the logits from the output
    logits = outputs[0]
    # apply softmax to get the probabilities
    probs = torch.softmax(logits, dim=1)
    # get the predicted label index (i.e., the index with the highest probability)
    predicted_label_index = torch.argmax(probs, dim=1).item()
    X_train_features.append(probs.detach().numpy())
    
    # print('---------------------')
    # print('i: ', i)
    # if predicted_label_index == 0:
    #     print('severe')
    # elif predicted_label_index ==1:
    #     print('moderate')
    # elif predicted_label_index ==2:
    #     print('not depression')    
    # else:
    #     print('no label')    
    # print('PHQ is: ', y_train[i])
    # print('probs: ', probs)
    
    # X_train_features.append(outputs[0].detach().numpy())

    if i % 100 == 0:
        print(i)

# extract features from dev data
X_dev_features = []
for i in range(len(X_dev)):
    # print('i dev: ', i)
    input_ids = torch.tensor(tokenizer.encode(X_dev[i], add_special_tokens=True)).unsqueeze(0)  # Batch size 1
    outputs = model(input_ids)

    # get the logits from the output
    logits = outputs[0]
    # apply softmax to get the probabilities
    probs = torch.softmax(logits, dim=1)
    # get the predicted label index (i.e., the index with the highest probability)
    predicted_label_index = torch.argmax(probs, dim=1).item()
    X_dev_features.append(probs.detach().numpy())

    # X_dev_features.append(outputs[0].detach().numpy())
    if i % 100 == 0:
        print(i)

# extract features from test data
X_test_features = []
for i in range(len(X_test)):
    # print('i test: ', i)
    input_ids = torch.tensor(tokenizer.encode(X_test[i], add_special_tokens=True)).unsqueeze(0)  # Batch size 1
    outputs = model(input_ids)

    # get the logits from the output
    logits = outputs[0]
    # apply softmax to get the probabilities
    probs = torch.softmax(logits, dim=1)
    # get the predicted label index (i.e., the index with the highest probability)
    predicted_label_index = torch.argmax(probs, dim=1).item()
    X_test_features.append(probs.detach().numpy())

    # X_test_features.append(outputs[0].detach().numpy())
    if i % 100 == 0:
        print(i)  
        

163
56
56
0
100
0
0


In [58]:
print(X_train_features[2].shape)
print(X_dev_features[2].shape)
print(X_test_features[10].shape)


(1, 3)
(1, 3)
(1, 3)


In [59]:
X_train_features

[array([[0.04594771, 0.73226935, 0.22178294]], dtype=float32),
 array([[0.01544387, 0.12209383, 0.8624622 ]], dtype=float32),
 array([[0.00854682, 0.16256104, 0.8288921 ]], dtype=float32),
 array([[0.7878974, 0.1019187, 0.1101839]], dtype=float32),
 array([[0.11958139, 0.30254945, 0.5778692 ]], dtype=float32),
 array([[0.5143548 , 0.44336036, 0.04228478]], dtype=float32),
 array([[0.72259307, 0.2442132 , 0.03319371]], dtype=float32),
 array([[0.03341649, 0.21408467, 0.75249887]], dtype=float32),
 array([[0.78910667, 0.13773926, 0.07315407]], dtype=float32),
 array([[0.01476022, 0.09589555, 0.8893443 ]], dtype=float32),
 array([[0.04109652, 0.10564982, 0.85325366]], dtype=float32),
 array([[0.02030646, 0.0707326 , 0.90896094]], dtype=float32),
 array([[0.00798201, 0.16224383, 0.8297741 ]], dtype=float32),
 array([[0.03640566, 0.68157387, 0.28202045]], dtype=float32),
 array([[0.0067701 , 0.10678197, 0.88644797]], dtype=float32),
 array([[0.5816213 , 0.21935636, 0.19902238]], dtype=float

In [60]:
# convert to numpy arrays
deproberta_features_train = np.array(X_train_features)
deproberta_features_dev = np.array(X_dev_features)
deproberta_features_test = np.array(X_test_features)

print('train shape: ', np.shape(deproberta_features_train))
print('dev shape: ', np.shape(deproberta_features_dev))
print('test shape: ', np.shape(deproberta_features_test))

# deproberta_features_train = np.concatenate((X_train_features, X_dev_features), axis=0)
# print('train shape: ', np.shape(deproberta_features_train))

# reshape the features
deproberta_features_train = deproberta_features_train.reshape(deproberta_features_train.shape[0], deproberta_features_train.shape[2])
deproberta_features_dev = deproberta_features_dev.reshape(deproberta_features_dev.shape[0], deproberta_features_dev.shape[2])
deproberta_features_test = deproberta_features_test.reshape(deproberta_features_test.shape[0], deproberta_features_test.shape[2])


train shape:  (163, 1, 3)
dev shape:  (56, 1, 3)
test shape:  (56, 1, 3)


In [64]:
# train a SVR model on the bert_features and PHQ_Score as the target
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold

X_train = np.array(deproberta_features_train)
X_dev = np.array(deproberta_features_dev)
X_test = np.array(deproberta_features_test)
y_train = np.array(df_train['PHQ_Score'])
y_dev = np.array(df_dev['PHQ_Score'])
# y_train = np.concatenate((y_train, y_dev), axis=0)
y_test = np.array(df_test['PHQ_Score'])

print(X_train.shape)
print(X_dev.shape)
print(X_test.shape)

# normalize X_train, X_dev and X_test
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_dev = scaler.transform(X_dev)
X_test = scaler.transform(X_test)

# train a SVR model on X_train and y_train
# svr = SVR(kernel='rbf', C=2, gamma=0.1)
svr = SVR(kernel='rbf', C=7, gamma='scale')
# svr = SVR(kernel='poly', degree=3, C=0.1, gamma='scale', coef0=1)

svr.fit(X_train, y_train)

# predict on X_train and calculate the mean squared error and mean absolute error
y_pred = svr.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
mae = mean_absolute_error(y_train, y_pred)
print('rmse for train: ', np.sqrt(mse))
print('mae for train: ', mae)

# # print y_train together with y_pred from Train set
# for i in range(len(y_train)):
#     if abs(y_train[i] - y_pred[i]) > 5:
#         print('i:', i, ' ', y_train[i], ' , ', y_pred[i])

# predict on X_dev and calculate the mean squared error and mean absolute error
y_pred = svr.predict(X_dev)
mse = mean_squared_error(y_dev, y_pred)
mae = mean_absolute_error(y_dev, y_pred)
print('rmse for dev: ', np.sqrt(mse))
print('mae for dev: ', mae)

# print y_dev together with y_pred from Dev set
# for i in range(len(y_dev)):
#     if abs(y_dev[i] - y_pred[i]) > 5:
#         print('i:', i, ' ', y_dev[i], ' , ', y_pred[i])

# predict on X_dev and calculate the mean squared error and mean absolute error
y_pred = svr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print('rmse for test: ', np.sqrt(mse))
print('mae for test: ', mae)

# # print y_test together with y_pred from Test set
# for i in range(len(y_test)):
#     if abs(y_test[i] - y_pred[i]) > 5:
#         print('i:', i, ' ', y_test[i], ' , ', y_pred[i])

(163, 3)
(56, 3)
(56, 3)
rmse for train:  5.910561780143632
mae for train:  4.384149544556507
rmse for dev:  5.42441007511439
mae for dev:  4.1321841993205926
rmse for test:  6.528515615032282
mae for test:  5.084523139254406


In [93]:
df_train.dtypes

id                int64
Gender           object
PHQ_Binary        int64
PHQ_Score         int64
PCL-C (PTSD)      int64
PTSD Severity     int64
text             object
completions      string
dtype: object

In [66]:
# I tried classification but results were really bad. No PHQ_Binary = 1 has been detected!
# # train a classifier on the bert_features and PHQ Binary as the target
# from sklearn.svm import SVC
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# from sklearn.metrics import classification_report

# X_train = np.array(deproberta_features_train)
# X_dev = np.array(deproberta_features_dev)
# X_test = np.array(deproberta_features_test)

# y_train = np.array(df_train['PHQ_Binary'])
# y_dev = np.array(df_dev['PHQ_Binary'])
# y_test = np.array(df_test['PHQ_Binary'])

# print(X_train.shape)
# print(X_dev.shape)
# print(X_test.shape)

# # normalize X_train, X_dev and X_test
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_dev = scaler.transform(X_dev)
# X_test = scaler.transform(X_test)

# # train an SVM classifier
# clf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
# clf.fit(X_train, y_train)

# # make predictions on the dev set
# y_dev_pred = clf.predict(X_dev)

# # evaluate performance on the dev set
# accuracy = accuracy_score(y_dev, y_dev_pred)
# precision = precision_score(y_dev, y_dev_pred, average='binary', pos_label=1)
# recall = recall_score(y_dev, y_dev_pred, average='binary', pos_label=1)
# f1 = f1_score(y_dev, y_dev_pred, average='binary', pos_label=1)
# print(f'Dev set metrics: accuracy={accuracy:.3f}, precision={precision:.3f}, recall={recall:.3f}, F1={f1:.3f}')

# # make predictions on the test set
# y_test_pred = clf.predict(X_test)

# # evaluate performance on the test set
# accuracy = accuracy_score(y_test, y_test_pred)
# precision = precision_score(y_test, y_test_pred, average='binary', pos_label=1)
# recall = recall_score(y_test, y_test_pred, average='binary', pos_label=1)
# f1 = f1_score(y_test, y_test_pred, average='binary', pos_label=1)
# print(f'Test set metrics: accuracy={accuracy:.3f}, precision={precision:.3f}, recall={recall:.3f}, F1={f1:.3f}')

# # print classification report
# print('classification report y_dev: ')
# print(classification_report(y_dev, y_dev_pred))

# # print classification report
# print('classification report y_test: ')
# print(classification_report(y_test, y_test_pred))

(163, 3)
(56, 3)
(56, 3)
Dev set metrics: accuracy=0.786, precision=0.000, recall=0.000, F1=0.000
Test set metrics: accuracy=0.696, precision=0.000, recall=0.000, F1=0.000
classification report y_dev: 
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        44
           1       0.00      0.00      0.00        12

    accuracy                           0.79        56
   macro avg       0.39      0.50      0.44        56
weighted avg       0.62      0.79      0.69        56

classification report y_test: 
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        39
           1       0.00      0.00      0.00        17

    accuracy                           0.70        56
   macro avg       0.35      0.50      0.41        56
weighted avg       0.49      0.70      0.57        56



/Users/misha/My_Projects/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/misha/My_Projects/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/misha/My_Projects/venv/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/misha/My_Projects/venv/lib/python3.9/site-pac

In [79]:
# trying Bag of words (BoW) approach
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LinearRegression

train_text = df_train['completions'].tolist()
dev_text = df_dev['completions'].tolist()
test_text = df_test['completions'].tolist()

vectorizer = CountVectorizer()
vectorizer.fit(train_text)

train_bow = vectorizer.transform(train_text)
dev_bow = vectorizer.transform(dev_text)
test_bow = vectorizer.transform(test_text)

X_train = train_bow.toarray()
X_dev = dev_bow.toarray()
X_test = test_bow.toarray()

print(len(X_train))
print(len(X_dev))
print(len(X_test))

y_train = np.array(df_train['PHQ_Score'])
y_dev = np.array(df_dev['PHQ_Score'])
y_test = np.array(df_test['PHQ_Score'])

svr = SVR(kernel='rbf', C=2, gamma='scale')
svr.fit(X_train, y_train)

# Evaluate the model on the dev set
y_pred = svr.predict(X_dev)
mse = mean_squared_error(y_pred, y_dev)
mae = mean_absolute_error(y_pred, y_dev)
print('rmse for dev: ', np.sqrt(mse))
print('mae for dev: ', mae)


163
56
56
rmse for dev:  5.582438651257683
mae for dev:  4.440498014486063


In [149]:
# train on train and dev
# convert to numpy arrays
deproberta_features_train = np.array(X_train_features)
deproberta_features_dev = np.array(X_dev_features)
deproberta_features_test = np.array(X_test_features)

print('train shape: ', np.shape(deproberta_features_train))
print('dev shape: ', np.shape(deproberta_features_dev))

deproberta_features_train = np.concatenate((X_train_features, X_dev_features), axis=0)

print('train shape: ', np.shape(deproberta_features_train))

# reshape the features
deproberta_features_train = deproberta_features_train.reshape(deproberta_features_train.shape[0], deproberta_features_train.shape[2])
# deproberta_features_dev = deproberta_features_dev.reshape(deproberta_features_dev.shape[0], deproberta_features_dev.shape[2])
deproberta_features_test = deproberta_features_test.reshape(deproberta_features_test.shape[0], deproberta_features_test.shape[2])

train shape:  (163, 1024)
dev shape:  (56, 1024)
train shape:  (219, 1024)


IndexError: tuple index out of range

In [43]:
# train on train and dev

# train a SVR model on the bert_features and PHQ_Score as the target
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import KFold

X_train = np.array(deproberta_features_train)
X_dev = np.array(deproberta_features_dev)
X_test = np.array(deproberta_features_test)
y_train = np.array(df_train['PHQ_Score'])
y_dev = np.array(df_dev['PHQ_Score'])
y_train = np.concatenate((y_train, y_dev), axis=0)
y_test = np.array(df_test['PHQ_Score'])

# normalize X_train, X_dev and X_test
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
# X_dev = scaler.transform(X_dev)
X_test = scaler.transform(X_test)

# train a SVR model on X_train and y_train
# svr = SVR(kernel='rbf', C=2, gamma=0.1)
svr = SVR(kernel='rbf', C=5, gamma=0.1)
svr.fit(X_train, y_train)

# predict on X_train and calculate the mean squared error and mean absolute error
y_pred = svr.predict(X_train)
mse = mean_squared_error(y_train, y_pred)
mae = mean_absolute_error(y_train, y_pred)
print('rmse for train: ', np.sqrt(mse))
print('mae for train: ', mae)

# predict on X_dev and calculate the mean squared error and mean absolute error
# y_pred = svr.predict(X_dev)
# mse = mean_squared_error(y_dev, y_pred)
# mae = mean_absolute_error(y_dev, y_pred)
# print('rmse for dev: ', np.sqrt(mse))
# print('mae for dev: ', mae)

# predict on X_dev and calculate the mean squared error and mean absolute error

y_pred = svr.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
print('rmse for test: ', np.sqrt(mse))
print('mae for test: ', mae)

rmse for train:  5.4572524976891135
mae for train:  3.979344948542748
rmse for test:  6.0754504853236355
mae for test:  4.862346661752325


In [161]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Define the parameter grid to search over
param_grid = {
    'C': [0.1, 1, 2, 5, 10, 20, 100],
    'gamma': [0.01, 0.1, 1, 2, 5, 10, 100],
    'kernel': ['linear', 'rbf']
}

# Create a support vector regression object
svr = SVR()

# Create a GridSearchCV object
grid_search = GridSearchCV(estimator=svr, param_grid=param_grid, cv=5)

# Fit the GridSearchCV object to the data
grid_search.fit(X_train, y_train)

# Print the best hyperparameters
print("Best hyperparameters:", grid_search.best_params_)

y_pred = grid_search.predict(X_train)
rmse = np.sqrt(mean_squared_error(y_train, y_pred))
mae = mean_absolute_error(y_train, y_pred)
print("RMSE Train:", rmse)
print("MAE Train:", mae)

# Make predictions on the testing set using the best model
y_pred = grid_search.predict(X_dev)
# Calculate the root mean squared error and mean absolute error
rmse = np.sqrt(mean_squared_error(y_dev, y_pred))
mae = mean_absolute_error(y_dev, y_pred)
print("RMSE Dev:", rmse)
print("MAE Dev:", mae)

# Make predictions on the testing set using the best model
y_pred = grid_search.predict(X_test)
# Calculate the root mean squared error and mean absolute error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)
print("RMSE Test:", rmse)
print("MAE Test:", mae)


Best hyperparameters: {'C': 0.1, 'gamma': 0.01, 'kernel': 'linear'}
RMSE Train: 6.341812750078263
MAE Train: 4.938036809815951
RMSE Dev: 6.610327417868843
MAE Dev: 5.696428571428571
RMSE Test: 6.6453528338015495
MAE Test: 5.803571428571429
